title: Developer
email: suhyunbaik89@gmail.com
description:
baseurl: ''
url: 'https://suhyunbaik.github.io'
twitter: ''
github: 'https://github.com/suhyunbaik'
instagram: ''
facebook: ''
markdown: kramdown
permalink: pretty
paginate: 60
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap
include:
  - _pages
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
defaults:
  - scope:
      path: _pages
    values:
      permalink: '/:basename:output_ext'
